Conditional resource highlighting
rdutta/runelite-gauntlet pull request #21
Opened 2022-09-30 21:11 UTC by Hyftar

This pull request adds a setting to remove the highlighting of resources  once they have been acquired in a run, thus making it easier to spot resources that still need to be obtained.

![java_rwdwLTafKf](https://user-images.githubusercontent.com/10182579/193355553-129a8db8-11ce-43be-a1a5-3d9f9aa5031a.gif)

The toggle-able setting can be found at the end of the `Resource Overlay` section.

I had to expose several class methods to make it possible to get the current resource count in the `SceneOverlay` class, let me know if it's a problem.

I'm participating in the 2022 Hacktoberfest, please add the `hacktoberfest-accepted` once this PR is approved. Thanks!

2022-10-10 04:42 UTC, Hyftar commented
@rdutta have you had the chance to check the pull request?

2022-10-10 05:29 UTC, rdutta requested changes

2022-10-10 05:29 UTC, rdutta commented on src/main/java/ca/gauntlet/resource/ResourceManager.java
> +	private final HashMap<String, ResourceCounter> resourceCounters = new HashMap<>();
Can the Resource be used as the key instead of the name?

2022-10-10 05:29 UTC, rdutta commented on src/main/java/ca/gauntlet/resource/ResourceManager.java
> +		return this.resourceCounters.get(resourceName).getCount();
Calling get() and doing a null check may be more efficient here

2022-10-10 05:49 UTC, rdutta requested changes

2022-10-10 05:49 UTC, rdutta commented on src/main/java/ca/gauntlet/overlay/SceneOverlay.java
> +	}
This method is better placed in the ResourceManager class

2022-10-10 05:57 UTC, Hyftar commented on src/main/java/ca/gauntlet/resource/ResourceManager.java
> +	private final HashMap<String, ResourceCounter> resourceCounters = new HashMap<>();
The problem here is that since the `Resource` enum in `ca.gauntlet.resource.Resource` is not public, I would have to expose it to the `SceneOverlay` class and possibly add a method to the `Resource` class to get the resource from a game id. If you don't see anything against that I'll go ahead with that approach.

2022-10-10 06:29 UTC, rdutta commented on src/main/java/ca/gauntlet/resource/ResourceManager.java
> +	private final HashMap<String, ResourceCounter> resourceCounters = new HashMap<>();
Moving `hasAcquiredResource()` into `ResourceManager` will avoid having to change visibility. I think you can also use ResourceType in the switch statement instead of grabbing the gameobject id.

2022-10-10 06:47 UTC, Hyftar commented
I applied your comments and I took the liberty to renamed the `Resource` class to `ResourceEntity` to avoid confusion with the `Resource` enum.

Let me know if there are more changes needed.

2022-10-10 07:19 UTC, rdutta requested changes

2022-10-10 07:19 UTC, rdutta commented on src/main/java/ca/gauntlet/resource/ResourceManager.java
> +
Can be simplified

```java
	public boolean hasAcquiredResource(ResourceEntity resourceEntity)
	{
		switch (resourceEntity.getGameObject().getId())
		{
			case ObjectID.CRYSTAL_DEPOSIT:
				return getResourceCount(Resource.CRYSTAL_ORE) < 1;
			case ObjectID.CORRUPT_DEPOSIT:
				return getResourceCount(Resource.CORRUPTED_ORE) < 1;
                        // Other normal/corrupted cases here
			default:
				return false;
		}
	}
```

Visibility for Resource can remain package-private

2022-10-10 07:21 UTC, rdutta commented
Please test this for all resources in both normal and corrupted gauntlet. I am unable to test myself currently.

2022-10-10 18:12 UTC, Hyftar commented on src/main/java/ca/gauntlet/resource/ResourceManager.java
> +
I would avoid combining the two methods into one to avoid the repetition of `< 1` with each object. Writing `Resource.CRYSTAL_ORE` is indeed a lot clearer though!

2022-10-10 18:27 UTC, Hyftar commented
Do you think we should enable this feature by default?

Here are my tests for each resource:

## Normal Gauntlet

### Ore
![java_Ex077tO0xC](https://user-images.githubusercontent.com/10182579/194929441-991ff31f-b93a-4d51-91aa-00b1a4a5775b.gif)

### Fish
![java_lyu7g5BwHL](https://user-images.githubusercontent.com/10182579/194929475-6869879c-b22c-4eed-bade-e35f9c424d45.gif)

### Grym Leaf
![java_mhaBsPbwl6](https://user-images.githubusercontent.com/10182579/194929522-3bfcb802-0ae0-43b4-98c1-1739d09150ad.gif)

### Bark
![java_sDQhZCDGq9](https://user-images.githubusercontent.com/10182579/194929582-0b22bbbe-cb04-4584-ae9c-ab3368ebec60.gif)

### Linum Tirinum
![java_0BdBM63sky](https://user-images.githubusercontent.com/10182579/194929649-aaf51b14-9b26-4f46-be7f-526d8cd90183.gif)

## Corrupted Gauntlet
### Ore
![java_aRFQkgPMT5](https://user-images.githubusercontent.com/10182579/194930086-848eb643-8ae5-4a78-9ed5-888d8f8f7d49.gif)

### Fish
![java_Uys5r3zFS1](https://user-images.githubusercontent.com/10182579/194930128-5933135f-7d75-44d6-89dd-559c9d69ec8b.gif)

### Grym Leaf
![java_MA7aR98SpH](https://user-images.githubusercontent.com/10182579/194930183-70d89b6d-55ed-45c0-b1ea-c07e39b68921.gif)

### Bark
![java_Pasx624sXd](https://user-images.githubusercontent.com/10182579/194930192-e1f59a65-5106-49c6-a132-e0065661e885.gif)

### Linum Tririnum
![java_ZWJZ0oLOKT](https://user-images.githubusercontent.com/10182579/194930218-4ff47cc4-2990-477e-9986-4b06fb4866b0.gif)

2022-10-12 02:32 UTC, rdutta approved these changes

2022-10-12 02:33 UTC, merged