WIP: Adding option to track resources upwards, rather than downward
rdutta/runelite-gauntlet pull request #34
Opened 2023-06-20 23:28 UTC by noxora

2023-06-20 23:30 UTC, noxora commented on src/main/java/ca/gauntlet/module/maze/ResourceCounter.java
> +	@Inject
This is currently broken and doesn't get populated, resulting in a null pointer in `resourceTarget()` below

2023-06-20 23:42 UTC, noxora commented on src/main/java/ca/gauntlet/module/maze/ResourceCounter.java
> +	@Inject
This has been fixed

2023-06-20 23:43 UTC, noxora commented
If someone could help me find a good way to only have the tracking boxes appear as resources are collected, rather than all at once at the beginning, that would be ideal. Otherwise this is good to go

2023-06-21 21:44 UTC, rdutta requested changes
Can you elaborate on your issue comment "fill the gap in functionality"? What is the benefit of incrementing the counter instead of decrementing it?

Related, there is a config `Dynamically remove overlays` that needs to be updated to handle incremental counting if this feature is accepted.

2023-06-21 21:44 UTC, rdutta commented on src/main/java/ca/gauntlet/module/maze/ResourceCounter.java
> +			case WEAPON_FRAME:
Missing case for corrupted weapon frame (?)

2023-06-21 21:52 UTC, noxora commented on src/main/java/ca/gauntlet/module/maze/ResourceCounter.java
> +			case WEAPON_FRAME:
That's correct, I need to fix that

2023-06-21 21:57 UTC, noxora commented
The "gap in functionality" is created by the plugin "Gauntlet" (https://runelite.net/plugin-hub/show/gauntlet) which many players use to track resources collected, rather than count down resource needs. Multiple guides that I watched online for gauntlet recommended installing both this plugin and the "Gauntlet" plugin, as well as Hunllef Helper, so I would assume they are often all downloaded together, and without any configuration of any of the plugins, the defaults appear to work well, with the highlighting and timer provided by this plugin, "Gauntlet" tracking resources collected in the maze and Hunllef helper keeping track in the fight. 

The sticking point is that "Gauntlet" hasn't been updated since May, 2020, and has multiple open issues, including the bug I initially reported here, thinking that this plugin was the cause. Since I believe "Gauntlet" to be unmaintained at this point, I think it would be good to offer players a working alternative to the functionality it provided.

2023-06-21 22:09 UTC, noxora commented
I've committed changes to add the dynamic highlighting functionality

2023-06-22 00:18 UTC, rdutta approved these changes

2023-06-22 00:26 UTC, rdutta commented
> The gap in functionality is created by the plugin "Gauntlet" (https://runelite.net/plugin-hub/show/gauntlet) which many players use to track resources collected, rather than count down resource needs. Multiple guides that I watched online for gauntlet recommended installing both this plugin and the "Gauntlet" plugin, as well as Hunllef Helper, so I would assume they are often all downloaded together, and without any configuration of any of the plugins, the defaults appear to work well, with the highlighting and timer provided by this plugin, "Gauntlet" tracking resources collected in the maze and Hunllef helper keeping track in the fight.
> 
> The sticking point is that "Gauntlet" hasn't been updated since May, 2020, and has multiple open issues, including the bug I initially reported here, thinking that this plugin was the cause. Since I believe "Gauntlet" to be unmaintained at this point, I think it would be good to offer players a working alternative to the functionality it provided.

I see that repo has not been updated in 3 years, so it might be best to simply replicate the feature for now. I have pushed some changes that keep the infobox counter color white and only creates boxes when a resource is collected. Any resource with a value of '0' will not be tracked in either tracking mode.

If you agree with these changes and it works as expected (please test) I can accept the PR.

2023-06-22 13:36 UTC, noxora commented
I agree with these changes, I noticed that dynamically removing overlays is now set to work only for decrement mode. As long as this is okay with you I'm happy. I tested the plugin in both regular and corrupted gauntlet, on both increment and decrement modes for each, and it seems to work as intended, with the behavior that we've talked about. Thank you for your help

2023-06-23 00:18 UTC, merged

2023-09-26 05:45 UTC, while-loop commented
Just digging through this plugin's repo. 
I'm [disabling](https://github.com/runelite/plugin-hub/pull/4963) the old Gaunlet plugin as this one is much better and includes much more features for players. Thanks for adding feature parity :+1: