Add option to disable boss room entry when holding uncooked fish
rdutta/runelite-gauntlet pull request #35
Opened 2023-09-01 10:17 UTC by Toocanzs

I kept forgetting to cook the fish before entering the boss. This PR adds an option to completely disable the Pass/Quick-Pass options so it is impossible to enter with uncooked fish.

2023-09-03 07:09 UTC, rdutta requested changes

2023-09-03 07:09 UTC, rdutta commented on src/main/java/ca/gauntlet/TheGauntletConfig.java
> +			description = "Disables the Pass and Quick-Pass options on the boss door if there are any uncooked fish in your inventory",
Change description to:

`description = "Deprioritizes \"Pass\" and \"Quick-Pass\" while carrying uncooked paddlefish.<br>" +
			"Disable any custom menu-entry swaps if applicable.",`

2023-09-03 07:09 UTC, rdutta commented on src/main/java/ca/gauntlet/module/maze/MazeModule.java
> +	}
This can be simplified,

```java
	@Subscribe()
	public void onMenuEntryAdded(final MenuEntryAdded event)
	{
		if (!config.utilitiesFishCheck() ||
			(!event.getOption().equals("Quick-pass") && !event.getOption().equals("Pass")))
		{
			return;
		}

		final ItemContainer container = client.getItemContainer(InventoryID.INVENTORY);

		if (container == null)
		{
			return;
		}

		final boolean hasRawFish = Arrays.stream(container.getItems()).anyMatch(x -> x.getId() == RAW_PADDLEFISH);

		if (!hasRawFish)
		{
			return;
		}

		event.getMenuEntry().setDeprioritized(true);
	}
```

2023-09-03 19:32 UTC, Toocanzs commented
The changes work, but it was quite confusing as to why the de-prioritize did nothing for me initially. 
Removing the custom menu entry swap fixed that. The only issue is there's no way to have both a left click Quick-pass and also remove the option when fish are uncooked. 

Somewhat defeats the purpose since you will build up muscle memory of always right clicking to quick pass, and the option will be there regardless of if the fish are cooked or not. I think it would be better to just remove the option, or replace with a "Cook fish!" option that does nothing when you click it. Unsure if there's a standard way to do this like the .setDeprioritized thing.

2023-09-03 22:53 UTC, rdutta commented
I see what you mean about muscle-memory possibly defeating the purpose. Maybe ask on the runelite discord dev channel about how to get menu entry changes to prioritize over the Menu Entry Swapper plugin. I know the `@Subscribe` annotation takes a priority arg, but it didn't seem to make a difference when I changed it to a low/high value.

Worst case you can revert back to how you were doing it before, just make sure the config check and option checks are done first so that an early return can be done before any unnecessary processing.

2023-09-05 16:47 UTC, Toocanzs commented
I've switched back to removing the options, this time with onPostMenuSort and early returns

2023-09-07 16:42 UTC, rdutta approved these changes

2023-09-07 16:42 UTC, merged